import google.generativeai as genai
from google.ai.generativelanguage_v1beta.types import content

genai.configure(api_key="AIzaSyA8GJLGxP6hwjCHCLYzOSdDYVn5Fx9s2iw")

# Create the model
generation_config = {
    "temperature": 0,
    "top_p": 0.95,
    "top_k": 40,
    "max_output_tokens": 8192,
    "response_mime_type": "text/plain",
}

model = genai.GenerativeModel(
    model_name="gemini-1.5-flash-8b",
    generation_config=generation_config,
)

pre_models_default = [
    "Nutritional Values always use 100 grams or 100 milliliters for base calculation. Every nutrition value that is given to you is based on 100 grams or 100 milliliters. Do not mention product gram when speaking about nutritional values. Also comment about good or bad for average customer. Do not include nutritional value table. Do not put labels like 'Ortalama bir tüketici için değerlendirme'",
    "input: {\n\t\"success\": true,\n\t\"product_name\": \"Indomie Tavuk Çeşnili Noodle (Bardak) 60G\",\n\t\"ingredients\": \"Hazır Noodle İçeriği: Buğday Unu, Bitkisel Yağ (Palm), Patates Nişastası, Tuz, Emülgatör (Yağ Asitlerinin Mono & Digliseritleri, Gliserol), Asitlik Düzenleyici (Disodyum Fosfat, Sodyum Tripolifosfat, Potasyum Karbonat), Kabartıcı (Sodyum Karonat), Kıvam Arttırıcı (Guar Gam) & Renklendirici (Riboflavin) Aroma Verici Karışım İçeriği: Tuz, Soğan Tozu, Aroma Arttırıcı (Monosodyum Glutamat), Yapay Tavuk Aroması (<%2), Biber Tozu, Palm Yağı Tozu, Sarımsak Tozu, Maya (S.cerevisiae), Karamel, Zencefil Tozu & Kırmızı Biber Tozu Garnitür: Tekstürize Bitki Proteini (Soya Fasulyesi) & Kurutulmuş Sebzeler\",\n\t\"nutritional_values\": {\n\t\t\"calories\": 464.0,\n\t\t\"fat\": 21.0,\n\t\t\"saturated_fat\": 12.0,\n\t\t\"carbohydrates\": 59.0,\n\t\t\"sugar\": 3.0,\n\t\t\"protein\": 9.7,\n\t\t\"salt\": 4.7\n\t}\n}",
    "output: Son dönemde ülkemizde yaygın şekilde satılmaya başlanan ve gençler tarafından tüketilmesiyle bilinen noodle ürünlerinden birini; Indomie Tavuk Aromalı Hazır Noodle ürününü inceleyeceğiz. Ürün 60 gr.’lık paketlerde satılmakta olup, 1,5 su bardağı yani yaklaşık 300 ml sıcak suyla karıştırılarak tüketilmektedir. Ürünün satıldığı kaba eklenen sıcak suyun yanı sıra baharat karışımı, kırmızı biber tozu ve garnitürün eklenmesiyle 3 dakikada hazırlanan ürün içeriğinde çok sayıda katkı maddesi içeriyor. Ürün daha önceki yıllarda Suudi Arabistan’dan ithal edilirken, rafta incelediğimiz kadarıyla artık Türkiye’de üretilerek satışa sunuluyor.\n\nÜrün içeriğine baktığımızda temel olarak hazır noodle, aroma verici karışım, kırmızı biber tozu ve garnitürden oluştuğunu anlıyoruz. Bu temel bileşenlerin oransal dağılımı tüketiciye beyan edilmiyor fakat üründe ilk sırada hazır noodle içeriği yer alıyor. Hazır noodle içinde ise ilk 3 sırada; Buğday unu, Palm yağı ve patates nişastası yer alıyor. Üründe ayrıca tuz, emülgatörler, asitlik düzenleyiciler ve kıvam arttırıcılar bulunuyor. Ürüne eklenen aroma verici karışım ise ilk 3 sırada; Tuz, Soğan tozu ve Aroma arttırıcı etkisiyle bilinen Monosodyum Glutamat içeriyor. Üründe %2’den daha az olduğu beyan edilen yapay tavuk aroma vericisi bulunuyor. Üründe tavuk aromasının yanı sıra aroma verici karışım içeriğinde beyaz biber, sarımsak tozu, zencefil tozu ile maya ve palm yağı tozu bulunuyor. Üründe ayrıca maya olarak ekmek yapımında da kullanıldığı bilinen S. cerevisiae yer almaktadır. Son olarak ürüne eklenen garnitür içeriğinde ise tekstüre bitki proteini başlığı altında soya fasulyesi proteini bulunduğunu da söylemek gerekiyor. Ürün garnitür içeriğinde ayrıca kurutulmuş taze soğan ve havuç içeriyor.Ürün bu haliyle tüketilmeye hazır 60 gr.’lık tek pakette 279 kcal enerji veriyor. Ürünün tek paketinde 35 gr. karbonhidrat ve 13 gr. yağ bulunuyor. Tek paket üründeki yağın 7 gramının doymuş yağ olduğu bilgisi doğrultusunda üründen alınan kalorinin %22,5’inin doymuş yağdan geldiği hesaplanıyor. Üründe ayrıca tek pakette 5 gr. protein yer alırken, tuz oranı ise 2,8 gr. olarak dikkat çekiyor. Ürün içeriğindeki lif oranı tüketiciye beyan edilmezken, üründe proteinden gelen kalori oranı da %7 düzeyinde kalıyor.",
    "input: {\n\t\"success\": true,\n\t\"product_name\": \"Züber Lokma Antep Fıstığı Kaplı Meyve Topu 96 G\",\n\t\"ingredients\": \"Hurma (%63), Fındık (%16), Antep Fıstığı (%9), Hindiba Kökü Lifi, Nohut Unu, Kakao Kitlesi (%7) (Kakao Tozu, Kakao Yağı), Deniz Tuzu\",\n\t\"nutritional_values\": {\n\t\t\"calories\": 379.0,\n\t\t\"fat\": 15.8,\n\t\t\"saturated_fat\": 4.3,\n\t\t\"carbohydrates\": 51.6,\n\t\t\"sugar\": 37.3,\n\t\t\"protein\": 8.6,\n\t\t\"fibre\": 16.0,\n\t\t\"salt\": 0.04\n\t}\n}",
    "output: Daha önce özel incelemeler kapsamında farklı çeşitlerini incelediğimiz Züber Lokma ürünlerinin bu sefer Antep Fıstığı kaplamalı meyve toplarını ineleyeceğiz. Ürün tam ismiyle; Antep fıstığı kaplı Kakaolu Fındık Kremalı Meyve Topu olarak geçiyor. Tabi Kakaolu Fındık Kreması deyince aklınıza hemen bazı ürünler geliyor fakat bu ürünün içeriğinde ne ilave şeker, ne ilave bitkisel yağ ne de katkı maddesi bulunuyor. Ürün 96 gr.’lık paketlerde satılıyor Alterna Gıda’nın İstanbul tesislerinde üretiliyor. Ürünün içeriğine baktığımızda çoğunlukla oranları verilmiş bileşenler olduğunu görüyoruz. Bu da tüketici farkındalığı ve bilgilendirilmesi açısından örnek teşkil ediyor. Ürün içeriğinde hurma, fındık, antep fıstığı ve kakao gibi temel bileşenlerin oranları mevzuata uygun olarak açıkça beyan ediliyor. Buna göre ürün ilk 3 sırada; %62 oranına Hurma, %16 oranında fındık ve %9 oranında antep fıstığı içeriyor. Üründe ilave şeker bulunmuyor ve doğal tatlandırıcı ve yüksek lif kaynağı olarak hurma %62 gibi yüksek bir seviyede yer alıyor. Üründe ayrıca fındık ve antep fıstığının oranları da sıradan bir kakaolu fındık kreması veya antep fıstıklı çikolatadan çok daha yüksek olarak göze çarpıyor. Üründe daha da önemlisi herhangi bir aroma verici bulunmuyor. Yani aldığınız tüm tatlar bileşenlerden gelen doğal tatlar olacaktır. Ürün ayrıca hindiba kökü lifi ve nohut unu içeriyor. Üründe %7 oranında kakao kitlesi bulunuyor. Ürün bu temel bileşenlerin yanısıra herhangi bir koruyucu, renklendirici ya da emülgatör vb. katkı maddesi içermiyor.Gelelim ürünün besin değerlerine! Ürünün 96 gr.’lık paketlerde satıldığını söylemiştik. Ürünün tek porsiyonu 30 gr. olarak belirtiliyor – ki bu da tek pakette 3 porsiyon ürün olduğunu gösteriyor. Ürün tek porsiyonda 114 kcal enerji veriyor. Tek porsiyon üründe 15,5 gr. Karbonhidrat ve 4,7 gr. yağ bulunuyor – ki dediğimiz gibi bu besin değerleri bileşenlerden doğal olarak geliyor. Yağın kaynağı fındık ve antep fıstığı olduğundan üründeki doymuş yağ oranı da tek porsiyonda sadece 1,3 gr. olarak dikkat çekiyor. Üründe ayrıca tek porsiyonda 2,6 gr. protein bulunuyor. Üründe bir tür prebiyotik de olan hindiba kökü lifi olduğunu söylemiştik. Bu doğal bileşenin ve ilk sıradaki hurmanın katkısıyla ürün 100 gr.’da tam 16 gr. lif bulunuyor – ki bu da 30 gr.’lık tek porsiyonda 4,8 gr. gibi yüksek bir orana denk geliyor. Yüksek lif oranı ve doğal bileşenlerden gelen besin değerlerinin etkisiyle ürünün sizi ve çocuklarınızı abur cuburlarda olduğu gibi çabuk acıktırmayacağı, kan şekerinizi ani yükseltmeyeceğini ve daha uzun süre tokluk hissi vereceğini söyleyebiliriz.",
    "input: {\n\t\"success\": true,\n\t\"product_name\": \"Ülker Çikolata Kadayıflı Dubai Lezzeti 93 G\",\n\t\"ingredients\": \"Şeker, Tam Yağlı Süttozu, Kakao Yağı, Kakao Kitlesi, Antep Fıstığı (%8,6), Bitkisel Yağlar (Palm, Palm Çekirdeği), Çıtır Kadayıf Parçacıkları (%6,4) [Buğday Unu, Şeker], Peyniraltı Suyu Tozu, Yağsız Süttozu, Maltodekstrin, Emülgatörler (Soya Lesitini, Amonyum Fosfatitler, Poligliserol Polirisinoleat), Tuz, Aroma Vericiler, Yağı Azaltılmış Kakao Tozu, Spirulina Ekstraktı. Kakao kuru maddesi en az %30'dur.\",\n\t\"nutritional_values\": {\n\t\t\"calories\": 535.0,\n\t\t\"fat\": 34.0,\n\t\t\"saturated_fat\": 16.0,\n\t\t\"carbohydrates\": 56.0,\n\t\t\"sugar\": 48.0,\n\t\t\"protein\": 7.7,\n\t\t\"fibre\": 2.2,\n\t\t\"salt\": 0.35\n\t}\n }",
    "output: Ürün içeriğine baktığımızda ilk sırada sofra şekeri olduğunu görüyoruz. Üründe ayrıca sırasıyla; tam yağlı süttozu, kakao yağı ve kakao kitlesi bulunuyor. Ürün içeriğinde %8,6 oranında Antep fıstığı ve %6,4 oranında Çıtır kadayıf parçacıkları yer alıyor. Bu haliyle 93 gr’lık tek pakette 8 gr Antep fıstığı ve 6 gr kadayıf parçacıkları bulunduğu hesaplanıyor. Üründe ayrıca içeriği bilinmeyen aroma vericiler yer alıyor. Bu aroma vericiler içeriğinde Antep fıstığı aroması ya da kadayıf aroması olup olmadığı tüketicilere beyan edilmiyor. Ürün bitkisel yağ olarak Palm yağı ve Palm çekirdeği yağı içeriyor. Bu da halihazırda tam yağlı süttozu da içeren üründeki doymuş yağ oranının yükselmesine sebep oluyor.Ürün bu haliyle 93 gr’lık tek pakette 497,5 kcal enerji verirken, tek paket üründe 44,6 gr şeker yani yaklaşık 22 küp şeker bulunuyor. Bunun yanında ürünün tek paketi 31,6 gr yağ ve 7,2 gr protein içeriyor. Üründeki doymuş yağ miktarı ise 93 gr’lık tek pakette 14,9 gr olarak hesaplanıyor. Buna göre üründen alınan kalorinin %27’sinin doymuş yağdan geldiği anlaşılıyor. Diğer yandan alınan kalorinin %35,8’inin ise basit şekerden geldiği hesaplanıyor. Üründe ayrıca tek pakette 2 lif bulunuyor. İlk bakışta bir çikolataya göre yüksek sayılabilecek bu lif oranının karşılığında alınan karbonhidrat ve şeker yüküne bakıldığında, bu haliyle tek paketteki lif oranının kan şekerinin dengede kalmasını sağlayabilecek nitelikte olamayacağı anlaşılıyor. Ürün içeriğinde ayrıca ürünün daha yeşil görünmesi için spirulica ekstraktı kullanıldığı görülüyor. Firmanın sosyal medyadaki tadına baktım, paramı kaptım hesaplarına yaptırdığı reklamlar çerçevesinde Antep fıstığı içeren ve ambalajında abartılı şekilde tüketiciye vurgulanan yeşil renkli çikolata içi sosun ise gerçekte bu kadar akışkan ve dolgun olmadığı görülüyor.",
]


def generate_analysis(product_info: dict):
    new_list = list(pre_models_default)
    new_list.append(str(product_info))
    new_list.append("output: ")
    response = model.generate_content(new_list)
    return response.text
